#This script will analyse the mutations per position in the multi fasta fiel generated by PMPNN
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

def main():
    ffolder = '../data/input/'
    fname = 'PMPNN_spike_af3.fa'
    ofolder = '../data/output/'

    flist = []

    f = open(ffolder + fname, 'r')
    data = f.readlines()
    f.close()

    #Convert fasta data into a pandas df
    for i in data:
        if i.startswith('>'):
            continue
        else:
            flist.append(list(i.rstrip().lstrip()))

    columns = [str(x) for x in range(1134)] #total colimns = total amino acid positions

    df = pd.DataFrame(flist, columns=columns)

    #unq_muts_counts = [len(pd.unique(df[position])) for position in columns]

    combined_series = pd.DataFrame()

    for i in columns:
        #df[i].value_counts().to_csv(ffolder+'unique_mutation_counts/'+i+'.csv')
        combined_series = pd.concat([combined_series, df[i].value_counts()], axis=1)
        #This will count amino acid occurences for each position

    combined_series.columns=columns

    combined_series[np.isnan(combined_series)] = 0

    #save the count and frequency data to csv files
    combined_series.to_csv(ofolder+'mutation_counts.csv') #saving raw counts

    combined_series = combined_series/562765 #Divide by total fasta sequences to get frequency

    combined_series.to_csv(ofolder+'mutation_frequencies.csv') #saving frequencies

    combined_series = combined_series.transpose() 

    combined_series.to_csv(ofolder+'mutation_frequencies_trasposed.csv') #transposed for further analysis

if __name__ == "__main__":
    main()